#!/bin/bash
if [[ "$PWD" = *docs ]]; then
    echo "Run this script from main PyNitride directory"
    exit
fi
cd docs
sphinx-apidoc -o . ../ ../examples ../setup.py  ../pynitride/external ../pynitride/crystruct -f -e
make html
#make latexpdf