#!/bin/bash
if [[ "$PWD" = *docs ]]; then
    echo "Run this script from main PyNitride directory"
    exit
fi

runapidoc=true
runlatex=false
for key in "$@"
do
    case $key in
        --static)
        runapidoc=false
        shift
        ;;
        --latex)
        runlatex=true
        shift
        ;;
        *)

        ;;
    esac
shift
done
cd docs
if $runapidoc ; then
    sphinx-apidoc -o . ../ ../examples ../setup.py  ../pynitride/external ../pynitride/crystruct ../tests/old -f -e
fi

make html

if $runlatex ; then
    make latexpdf
fi