#!/bin/bash
if [[ "$PWD" = *docs ]]; then
    echo "Run this script from main PyNitride directory"
    exit
fi
cd docs
sphinx-apidoc -o . ../ ../examples ../setup.py ../pynitride/poissolve ../pynitride/external ../pynitride/crystruct ../tests -f -e
make html
