name: Build Tests

on:
  push:
    branches:
      - dev
      - main
      - "release/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    uses: ./.github/workflows/build_wheels.yml
