name: Build Wheels

on:
  workflow_call:

jobs:
  build_wheels:
    name: Build wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
