name: Build Tests

on:
  push:
    branches:
      - develop
      - main
      - "release/**"
  pull_request:
    branches:
      - develop
      - main
      - "release/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    uses: ./.github/workflows/build_wheels.yml
