name: Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install -e ".[dev]" --no-deps
      - name: Check dependencies are satisfiable
        run: pip check
      - name: Check requirements.txt is up to date
        run: |
          pip-compile --no-strip-extras --no-annotate --no-allow-unsafe --no-header --extra dev -o requirements.txt pyproject.toml
          git diff --exit-code requirements.txt
      - name: Run pytest
        run: pytest tests/
      - name: Ensure docs build
        run: python sphinx/document.py
